In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [55]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, GRU
from tensorflow.keras.optimizers import Adam

ModuleNotFoundError: No module named 'tensorflow'

In [31]:
v_lstm_data = pd.read_csv("../dataset/outputs/time_series_sarimax.csv")
v_lstm_data.drop(labels = ["avg_price","first_diff_cnt","second_diff_cnt"],axis = 1,inplace = True)
v_lstm_data.set_index(keys = "date", drop=True, inplace = True)
v_lstm_data.loc["2015-11-30",['item_cnt_month']]=0
for lag,col in enumerate([f"lag_{i}" for i in range(1,35)],start = 1):
    v_lstm_data[col] = v_lstm_data["item_cnt_month"].shift(lag).fillna(0)

v_lstm_data

,item_cnt_month,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6,lag_7,lag_8,lag_9,...,lag_25,lag_26,lag_27,lag_28,lag_29,lag_30,lag_31,lag_32,lag_33,lag_34
date,,,,,,,,,,,,,,,,,,,,,
2013-01-31,131478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-02-28,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-03-31,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-04-30,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-05-31,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-06-30,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-07-31,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-08-31,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-09-30,133332.0,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-10-31,127541.0,133332.0,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-11-30,130009.0,127541.0,133332.0,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-12-31,183342.0,130009.0,127541.0,133332.0,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-01-31,116899.0,183342.0,130009.0,127541.0,133332.0,125291.0,116966.0,125381.0,106970.0,107190.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-02-28,109686.0,116899.0,183342.0,130009.0,127541.0,133332.0,125291.0,116966.0,125381.0,106970.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-03-31,115296.0,109686.0,116899.0,183342.0,130009.0,127541.0,133332.0,125291.0,116966.0,125381.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-04-30,96556.0,115296.0,109686.0,116899.0,183342.0,130009.0,127541.0,133332.0,125291.0,116966.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-05-31,97789.0,96556.0,115296.0,109686.0,116899.0,183342.0,130009.0,127541.0,133332.0,125291.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-06-30,97429.0,97789.0,96556.0,115296.0,109686.0,116899.0,183342.0,130009.0,127541.0,133332.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-07-31,91279.0,97429.0,97789.0,96556.0,115296.0,109686.0,116899.0,183342.0,130009.0,127541.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-08-31,102721.0,91279.0,97429.0,97789.0,96556.0,115296.0,109686.0,116899.0,183342.0,130009.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-09-30,99208.0,102721.0,91279.0,97429.0,97789.0,96556.0,115296.0,109686.0,116899.0,183342.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-10-31,107422.0,99208.0,102721.0,91279.0,97429.0,97789.0,96556.0,115296.0,109686.0,116899.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-11-30,117845.0,107422.0,99208.0,102721.0,91279.0,97429.0,97789.0,96556.0,115296.0,109686.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-12-31,168754.0,117845.0,107422.0,99208.0,102721.0,91279.0,97429.0,97789.0,96556.0,115296.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-01-31,110971.0,168754.0,117845.0,107422.0,99208.0,102721.0,91279.0,97429.0,97789.0,96556.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-02-28,84198.0,110971.0,168754.0,117845.0,107422.0,99208.0,102721.0,91279.0,97429.0,97789.0,...,131478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-03-31,82014.0,84198.0,110971.0,168754.0,117845.0,107422.0,99208.0,102721.0,91279.0,97429.0,...,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-04-30,77827.0,82014.0,84198.0,110971.0,168754.0,117845.0,107422.0,99208.0,102721.0,91279.0,...,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-05-31,72295.0,77827.0,82014.0,84198.0,110971.0,168754.0,117845.0,107422.0,99208.0,102721.0,...,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-06-30,64114.0,72295.0,77827.0,82014.0,84198.0,110971.0,168754.0,117845.0,107422.0,99208.0,...,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0,0.0
2015-07-31,63187.0,64114.0,72295.0,77827.0,82014.0,84198.0,110971.0,168754.0,117845.0,107422.0,...,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0,0.0
2015-08-31,66079.0,63187.0,64114.0,72295.0,77827.0,82014.0,84198.0,110971.0,168754.0,117845.0,...,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0,0.0
2015-09-30,72843.0,66079.0,63187.0,64114.0,72295.0,77827.0,82014.0,84198.0,110971.0,168754.0,...,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0,0.0
2015-10-31,71056.0,72843.0,66079.0,63187.0,64114.0,72295.0,77827.0,82014.0,84198.0,110971.0,...,133332.0,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0,0.0
2015-11-30,0.0,71056.0,72843.0,66079.0,63187.0,64114.0,72295.0,77827.0,82014.0,84198.0,...,127541.0,133332.0,125291.0,116966.0,125381.0,106970.0,107190.0,147142.0,128090.0,131478.0

From Kaggle: [Simple and Easy Aprroach using LSTM](https://www.kaggle.com/code/karanjakhar/simple-and-easy-aprroach-using-lstm)

In [49]:
# X we will keep all columns except the first one
X_train_pre = v_lstm_data.iloc[:-1,1:]
# the first column is our label
y_train = v_lstm_data.values[:-1,0:1]

# for X_test we will predict Kaggle test set
X_test_pre = v_lstm_data.iloc[-1:,1:]

# lets have a look on the shape 
print(X_train.shape,y_train.shape,X_test.shape)

(34, 34) (34, 1) (1, 34)

In [50]:
ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train_pre)
X_test_sc = ss.transform(X_test_pre)

In [53]:
#expand dims
X_train = np.expand_dims(X_train_pre, axis = 2)
X_test = np.expand_dims(X_test_pre, axis = 2)

print(X_train.shape,y_train.shape,X_test.shape)

(34, 34, 1) (34, 1) (1, 34, 1)

In [54]:
model_lstm = Sequential()
model_lstm.add(LSTM(units = 64,input_shape = (34,1)))
model_lstm.add(Dropout(0.4))
model_lstm.add(Dense(1))

model_lstm.compile(loss = 'mse',optimizer = 'adam', metrics = ['mean_squared_error'])
model_lstm.summary()

NameError: name 'Sequential' is not defined

In [ ]:
model_lstm.fit(X_train,y_train,batch_size = 8482,epochs = 10)

In [ ]:
model_lstm.compile(optimizer=Adam(lr=.0005), loss='mse', metrics=['mean_squared_error'])

history = model_lstm.fit(train_sequences, validation_data=test_sequences, epochs=50, verbose=0)

In [ ]:
model = Sequential()
model.add(GRU(8, input_shape=input_shape, return_sequences=True)) # True if next layer is RNN
model.add(GRU(8, return_sequences=False)) # False if next layer is Dense

model.add(Dense(4, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

In [ ]:
my_model.fit(X_train,y_train,batch_size = 4096,epochs = 10)

In [14]:
424124/50

8482.48